apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sreeramsunkara
spec:
  profile:
    displayName: Sreeram Sunkara
    email: sunkarasr@vmware.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [default-team]
